shop/urls.py
from django.conf.urls import url
 
from shop import views
 
app_name = 'shop'
 
urlpatterns = [
 
    # /shop/
    url(r'^$', views.IndexView.as_view(), name='index'),
 
    # shop/product/entry
    url(r'^product/entry/$',views.ProductEntry.as_view(),name='product-entry'),
 
    # shop/product/2
    url(r'^product/(?P<pk>[0-9]+)/$', views.ProductUpdate.as_view(), name='product-update'),
 
    # shop/product/(?P<pk>[0-9]+)/delete
    url(r'^album/(?P<pk>[0-9]+)/delete$', views.ProductDelete.as_view(), name='product-delete'),
    # add to cart shop/product/(?P<pk>[0-9]+)/add
    url(r'^add/(?P<product_id>\w+)/(?P<quantity>\d{1,10})$', views.add_to_cart, name='add_to_cart'),
    #get cart items
    url(r'^cart/$', views.get_cart, name='get_cart'),
    #remove from cart
    url(r'^remove/(?P<product_id>\w+)/$', views.remove_from_cart, name='remove_from_cart'),

    url(r'^products/$',views.get_products,name='get_products')
 
]

testapp/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls import url
from my_app import views
from shop import views as shop_views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('register/', user_views.register, name='register'),
	path('profile/', user_views.profile, name='profile'),
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('my_app.urls')),
    url(r'^shop/',include('shop.urls')),
    #path('remove/', shop_views.remove_from_cart, name='remove_from_cart'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>A-SHOP</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    

</head>
<body>
<nav class="deep-orange darken-2">
    <div class="container nav-wrapper">
        <a href="{% url 'promo' %}" class="waves-effect waves-light brand-logo"><img src="/static/img/logo2.png"></a>
        <ul id="nav-mobile" class="waves-effect waves-light right">
            <li>
                <form action="{% url 'new_search'%}" method="post">
                    {% csrf_token %} 
                <div class="input-field">                    
                     <input name="search" type="search" placeholder="Introduce una busqueda"required>
                     <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                     <input type="submit" name="action">
                     <i class="material-icons">close</i>
                </div>
            </form>
            </li>
            {% if user.is_authenticated %}
              <li><a href="{% url 'shop:index'%}"><i class="large material-icons" style="color: black">apps</i></a></li>
              <li><a href="{% url 'shop:get_cart'%}"><i class="large material-icons" style="color: black">add_shopping_cart</i></a></li>
              <li><a href="{% url 'profile' %}"><i class="large material-icons" style="color: black">account_circle</i></a></li>
              <li><a href="{% url 'logout' %}"><i class="large material-icons" style="color: black">directions_run</i></a></li>
            {% else %}
              <li><a href="{% url 'login' %}"><i class="large material-icons" style="color: black">assignment_ind</i></a></li>
              <li><a href="{% url 'register' %}"><i class="large material-icons" style="color: black">add_circle</i></a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
    <!-- <h1 style="text-align: center">¿Que quieres buscar?</h1>
    <div class="row">
        <div class="col s4">
            
            <div class="center">
                <i class="large material-icons" style="color: #EE6E73">add_shopping_cart</i>
                <p>Busqueda de ofertas</p>
                <p class="light center">Adquiere las mejores ofertas de los mejores sitios.</p>
            </div>
        </div>

        <div class="col s4">
            
            <div class="center">
                <i class="large material-icons" style="color: orange">euro_symbol</i>
                <p>Precios regionales</p>
                <p class="light center">Obten los precios en tu moneda local.</p>
            </div>
        </div>

        <div class="col s4">
            
            <div class="center">
                <i class="large material-icons" style="color: blue">verified_user</i>
                <p>Seguridad de compras</p>
                <p class="light center">Sientete seguro al comprar.</p>
            </div>
        </div>
    </div>

	<form action="{% url 'new_search'%}" method="post">
		{% csrf_token %} 
		<input type="text" name="search" placeholder="Buscar">
		 <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    		<i class="material-icons right">send</i>
  		</button>
	</form> -->
{% if messages %}
    {% for message in messages %}
        <div class="card-panel green darken-1">
            {{ message }}
        </div>
    {% endfor %}        
{% endif %}
{% block content %}

{% endblock content %}
    
</div>
</body>
</html>