shop/urls.py
from django.conf.urls import url
 
from shop import views
 
app_name = 'shop'
 
urlpatterns = [
 
    # /shop/
    url(r'^$', views.IndexView.as_view(), name='index'),
 
    # shop/product/entry
    url(r'^product/entry/$',views.ProductEntry.as_view(),name='product-entry'),
 
    # shop/product/2
    url(r'^product/(?P<pk>[0-9]+)/$', views.ProductUpdate.as_view(), name='product-update'),
 
    # shop/product/(?P<pk>[0-9]+)/delete
    url(r'^album/(?P<pk>[0-9]+)/delete$', views.ProductDelete.as_view(), name='product-delete'),
    # add to cart shop/product/(?P<pk>[0-9]+)/add
    url(r'^add/(?P<product_id>\w+)/(?P<quantity>\d{1,10})$', views.add_to_cart, name='add_to_cart'),
    #get cart items
    url(r'^cart/$', views.get_cart, name='get_cart'),
    #remove from cart
    url(r'^remove/(?P<product_id>\w+)/$', views.remove_from_cart, name='remove_from_cart'),

    url(r'^products/$',views.get_products,name='get_products')
 
]

testapp/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls import url
from my_app import views
from shop import views as shop_views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('register/', user_views.register, name='register'),
	path('profile/', user_views.profile, name='profile'),
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('my_app.urls')),
    url(r'^shop/',include('shop.urls')),
    #path('remove/', shop_views.remove_from_cart, name='remove_from_cart'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-cart/cart/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType


class Cart(models.Model):
    creation_date = models.DateTimeField(verbose_name=_('creation date'))
    checked_out = models.BooleanField(default=False, verbose_name=_('checked out'))

    class Meta:
        verbose_name = _('cart')
        verbose_name_plural = _('carts')
        ordering = ('-creation_date',)

    def __unicode__(self):
        return unicode(self.creation_date)

class ItemManager(models.Manager):
    def get(self, *args, **kwargs):
        if 'product' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(type(kwargs['product']))
            kwargs['object_id'] = kwargs['product'].pk
            del(kwargs['product'])
        return super(ItemManager, self).get(*args, **kwargs)

class Item(models.Model):
    cart = models.ForeignKey(Cart, verbose_name=_('cart'), on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name=_('quantity'))
    unit_price = models.DecimalField(max_digits=18, decimal_places=2, verbose_name=_('unit price'))
    # product as generic relation
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()

    objects = ItemManager()

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('cart',)

    def __unicode__(self):
        return u'%d units of %s' % (self.quantity, self.product.__class__.__name__)

    def total_price(self):
        return self.quantity * self.unit_price
    total_price = property(total_price)

    # product
    def get_product(self):
        return self.content_type.get_object_for_this_type(pk=self.object_id)

    def set_product(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product))
        self.object_id = product.pk

    product = property(get_product, set_product)

shop/models.py
from django.db import models
# Create your models here.
from django.urls import reverse
 
class Product(models.Model):
    product_title = models.CharField(max_length=100)
    product_price = models.CharField(max_length=5)
    product_desc = models.CharField(max_length=100)
    product_image = models.ImageField(default='default.png', upload_to='product_files')
    def __str__(self):
        return f'{self.product_title}'
    # on submit click on the product entry page, it redirects to the url below. 
    def get_absolute_url(self):
        return reverse('shop:index')

django-cart/cart/views.py
# Create your views here.

shop/views.py
from django.shortcuts import render, redirect
# Create your views here.
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.core import serializers
from cart.cart import Cart
from django.http import JsonResponse, HttpResponse
# Create your views here.
from shop.models import Product
 
# view for the index page
class IndexView(generic.ListView):
    # name of the object to be used in the index.html
    context_object_name = 'product_list'
    template_name = 'shop/index.html'
 
    def get_queryset(self):
        return Product.objects.all()
 
# view for the product entry page
# @login_required
class ProductEntry(CreateView):
    model = Product
    # the fields mentioned below become the entry rows in the generated form
    fields = ['product_title', 'product_price', 'product_desc', 'product_image']
 
# view for the product update page
# @login_required
class ProductUpdate(UpdateView):
    model = Product
    # the fields mentioned below become the entyr rows in the update form
    fields = ['product_title', 'product_price', 'product_desc', 'product_image']
 
# view for deleting a product entry
# @login_required
class ProductDelete(DeleteView):
    model = Product
    # the delete button forwards to the url mentioned below.
    success_url = reverse_lazy('shop:index')


#Shopping cart
def add_to_cart(request, product_id, quantity):
    if request.method == 'POST':
        product = Product.objects.get(id=product_id)
        cart = Cart(request)
        cart.add(product, product.product_price, quantity)
        subtotal = cart.summary()
        total_items = cart.count()
        return render(request, 'shop/cart.html', {'cart': Cart(request), 'subtotal': subtotal, 'total_items': total_items})
    else:
        return redirect('shop')
   

def remove_from_cart(request, product_id):
    if request.method == 'POST':
        product = Product.objects.get(id=product_id)
        cart = Cart(request)
        cart.remove(product)
        subtotal = cart.summary()
        total_items = cart.count()
        # data = {"results": {
        # "product title": product.product_title,
        # "product desc": product.product_desc
        # }}
        #return JsonResponse(data)
        return render(request, 'shop/cart.html', {'cart': Cart(request), 'subtotal': subtotal, 'total_items': total_items})
    else:
        return redirect('shop:index')
    

def get_cart(request):
    cart = Cart(request)
    subtotal = cart.summary()
    total_items = cart.count()
    return render(request, 'shop/cart.html', {'cart': Cart(request), 'subtotal': subtotal, 'total_items': total_items})

def get_products(request):
    products = Product.objects.all()
    product_list =serializers.serialize('json', products)
    # for product in product_list:
    #     data = {"Products":{
    #     "product_title": product.product_title,
    #     "product_desc": product.product_desc
    #     }}
    return HttpResponse(product_list, content_type="text/json-comment-filtered")

shop/templates/shop/cart.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
      <div class="col s12 m7"><span class="flow-text">Products({{total_items}})</span>
        {% for item in cart %}
        <div class="card card-cart horizontal hoverable">
      <div class="card-image">
        <img src="{{ item.product.product_image.url }}">
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <p>{{ item.product.product_title }}.</p>
          <p>Cantidad:{{ item.quantity }}</p>
          <p>Precio:${{ item.total_price }}</p>
          <div class="card-action">
                <form action="{% url 'shop:remove_from_cart' product_id=item.product.id%}" method="POST" style="display: inline;">
                             {% csrf_token %}
                             <button  onclick="M.toast({html: 'Product deleted'})" type="submit" class="waves-effect waves-light btn-large red"><i class="material-icons right">backspace</i>Eliminar</button>
                </form>     
        </div>
        </div>
      </div>
    </div>
    {% endfor %}
    </div>
      <div class="col s5"><span class="flow-text">Total</span>
        <table class="responsive-table">
             <tr>
                 <th>Product</th>
                 <th>Quantity</th>
                 <th>Total Price</th>
             </tr>
             {% for item in cart %}
             <tr>
                 <td>{{ item.product.product_title }}</td>
                 <td>{{ item.quantity }}</td>
                 <td>{{ item.total_price }}</td>
             </tr>
             {% endfor %}
         </table>
      <h5 class="right-align">Total:${{subtotal}}</h5>
      <button onclick="M.toast({html: 'Purchase completed'})" class="waves-effect waves-light btn-large"><i class="material-icons right">attach_money</i>Comprar</button>
      </div>
    </div>

   
{% endblock content %}

shop/templates/shop/form_template.html
{% for field in form %}
    <div class="form-group">
        <div >
            <span class="text-danger la">{{ field.errors }}</span>
        </div>
        <label  >{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

shop/templates/shop/index.html
{% extends "base.html" %}
{% block content %}
<br>
{% if product_list %}
 <div class="row">
        {% for product in product_list %}
            <div class="col s4 m6 l4">
                <div class="card hoverable ">
                    <div class="card-image">
                        <img class="responsive-img activator" src="{{ product.product_image.url }}">
                    </div>
                    <div class="card-content">
                        <span class="activator">{{ product.product_title }}</span>
                        <p class="grey-text">Precio ${{ product.product_price }}</p>
                        <form action="{% url 'shop:add_to_cart' product_id=product.id quantity=1%}" method="post" style="display: inline;">
                             {% csrf_token %}
                          <button type="submit" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></button>
                        </form>                   
                    </div>
                    <div class="card-reveal">
                          <span class="card-title grey-text text-darken-4">{{ product.product_title }}<i class="material-icons right">close</i></span>
                          <p>{{ product.product_desc }}</p>
                        </div>
                    <div class="card-action">
                                {% if user.is_superuser %}
                                    <form action="{% url 'shop:product-delete' product.id %}" method="POST" style="display: inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-default btn-sm">Delete</button>
                                </form>
                                <form action="{% url 'shop:product-update' product.id  %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-default btn-sm">Update</button>
                                </form>
                                {% else %}
                                    <button type="submit" class="btn btn-default btn-sm activator ">Ver producto</button>
                                {% endif %}

                    </div>     
                </div>

            </div>

{% endfor %}
    </div>
 
    {% else %}
    <h1>No product entries found on the database.</h1>
 
 
{% endif %}
     {% if user.is_superuser %}
     <form action="{% url 'shop:product-entry'  %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button style="position: fixed;bottom: 20;right: 20;"type="submit" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></button>
        </form>
     {% endif %}
{% endblock content %}

shop/templates/shop/product_form.html
{% extends "base.html" %}
<!-- {% load crispy_forms_tags %} -->
{% block content %}
 <h3>Add a New Product</h3>
 
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'shop/form_template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>
{% endblock content %}